version: "3.8"

services:
  uv-pricecloud-api-01:
    container_name: "uv-pricecloud-${ENV}-api-01"
    image: "uv-pricecloud-${ENV}-api-01"
    restart: always
    environment:
      ENV: ${ENV}
      TZ: ${TZ}
      API_PORT: ${API_PORT}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_JWT_EXPIRATION_TIME: ${API_JWT_EXPIRATION_TIME}
      API_COOKIE_EXPIRATION_TIME: ${API_COOKIE_EXPIRATION_TIME}
      API_COOKIE_DOMAIN: ${API_COOKIE_DOMAIN}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SECRET: ${DB_SECRET}
      DB_IV: ${DB_IV}
      DB02_HOST: ${DB02_HOST}
      DB02_PORT: ${DB02_PORT}
      DB02_USER: ${DB02_USER}
      DB02_PASSWORD: ${DB02_PASSWORD}
      DB02_NAME: ${DB02_NAME}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      COMMON_SECRET: ${COMMON_SECRET}
      COMMON_IV: ${COMMON_IV}
      LIB_CLOUD_HOST: ${LIB_CLOUD_HOST}
      API03_HOST: ${API03_HOST}
      API03_PORT: ${API03_PORT}
      API02_HOST: ${API02_HOST}
      API02_PORT: ${API02_PORT}
    build:
      context: ./api-01
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
    depends_on:
      - uv-pricecloud-api-02
      - uv-pricecloud-api-03
    networks:
      - uv-pricecloud

  uv-pricecloud-db-01:
    container_name: "uv-pricecloud-${ENV}-db-01"
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - "../uv-pricecloud-${ENV}-db-01:/var/lib/postgresql/data"
    networks:
      - uv-pricecloud

  uv-pricecloud-api-02:
    container_name: "uv-pricecloud-${ENV}-api-02"
    restart: always
    build:
      context: ./api-02
      dockerfile: Dockerfile
    image: "uv-pricecloud-${ENV}-api-02"
    environment:
      INFRACOST_API_KEY: ${INFRACOST_API_KEY}
      SELF_HOSTED_INFRACOST_API_KEY: ${SELF_HOSTED_INFRACOST_API_KEY}
      DB02_HOST: ${DB02_HOST}
      DB02_USER: ${DB02_USER}
      DB02_PASSWORD: ${DB02_PASSWORD}
      DB02_NAME: ${DB02_NAME}
      TZ: ${TZ}
    depends_on:
      - uv-pricecloud-db-02
    networks:
      - uv-pricecloud

  uv-pricecloud-db-02:
    restart: always
    container_name: "uv-pricecloud-${ENV}-db-02"
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB02_USER}
      POSTGRES_PASSWORD: ${DB02_PASSWORD}
      POSTGRES_DB: ${DB02_NAME}
      TZ: ${TZ}
    volumes:
      - "../uv-pricecloud-${ENV}-db-02:/var/lib/postgresql/data"
    networks:
      - uv-pricecloud

  uv-pricecloud-api-03:
    container_name: "uv-pricecloud-${ENV}-api-03"
    restart: always
    image: "uv-pricecloud-${ENV}-api-03"
    build:
      context: ./api-03
      dockerfile: Dockerfile
    networks:
      - uv-pricecloud

  uv-pricecloud-ui:
    container_name: "uv-pricecloud-${ENV}-ui"
    image: "uv-pricecloud-${ENV}-ui"
    restart: always
    environment:
      NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST}
      UI_PORT: ${UI_PORT}
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_HOST: ${NEXT_PUBLIC_API_HOST}
        UI_PORT: ${UI_PORT}
    depends_on:
      - uv-pricecloud-api-01
    networks:
      - uv-pricecloud

networks:
  uv-pricecloud:
    name: uv-pricecloud-${ENV}
