version: "3.8"

services:
  uv-pricecloud-api-01:
    container_name: uv-pricecloud-api-01
    image: uv-pricecloud-api-01
    restart: always
    environment:
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_JWT_EXPIRATION_TIME: ${API_JWT_EXPIRATION_TIME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SECRET: ${DB_SECRET}
      DB_IV: ${DB_IV}
      ENV: ${ENV}
    build:
      context: ./api-01
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT}
    #    ports:
    #      - 9010:${API_PORT}
        depends_on:
          - uv-pricecloud-db

    networks:
      - uv-pricecloud

  uv-pricecloud-db:
    container_name: uv-pricecloud-db
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    volumes:
      - ../db-files:/var/lib/postgresql/data
#    ports:
#      - 9020:5432
    networks:
      - uv-pricecloud
#
#  uv-pricecloud-api-02:
#    container_name: uv-pricecloud-api-02
#    image: uv-pricecloud-api-02
#    restart: always
#    build:
#      context: ./api-02
#      dockerfile: Dockerfile
##    ports:
##      - 9011:5000
#    depends_on:
#      - uv-pricecloud-db
#    networks:
#      - uv-pricecloud
#
#
#  uv-pricecloud-ui:
#    container_name: uv-pricecloud-ui
#    image: uv-pricecloud-ui
#    restart: always
#    environment:
#      REACT_APP_UI_PORT: ${REACT_APP_UI_PORT}
#      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
#    build:
#      context: ./ui
#      dockerfile: Dockerfile
#      args:
#        REACT_APP_UI_PORT: ${REACT_APP_UI_PORT}
#        REACT_APP_API_HOST: ${REACT_APP_API_HOST}
#    depends_on:
#      - uv-pricecloud-api-01
##    ports:
##      - 9030:${REACT_APP_UI_PORT}
#    networks:
#      - uv-pricecloud
#
networks:
  uv-pricecloud:
    name: uv-pricecloud
